### ISSUE TITLE
[Question] Who/what is this app for?

### ISSUE THREAD

**Issue by pitsi** [pcolby/nfc-quick-settings#16]
The above is an honest question.
I own 2 devices with nfc, one running android 9 and one runninng android 12, both with stock android (android one and crdroid respectively), and the os already provides a button for enabling/disabling nfc right from the quick settings. And, afaik, the button is still there on android 13 and 14 too.

So what more does the app offer to the user? For instance, I also have an app that provides a quick settings button for enabling/disabling custom dns. This is not something the os itself provides, so yea, that app offers something useful to the user.

I respect your work on the app, don't get me wrong on that, I am just curious.

**Comment by pcolby** [comment]
Hi @pitsi. it's a good question.  I wrote it for myself, because I have a Pixel 6 which (for reasons known only to Google 🙄) doesn't have an NFC quick settings tile.

Here's an old support post where I originally asked about it, before deciding to white NFC Quick Settings myself: https://support.google.com/pixelphone/thread/223215355/quickly-switch-off-nfc-or-make-device-unlock-truly-required

Of course, as you point out, lots (most?) Android phones have an equivalent tile already, so I don't expect many people would find this one helpful. But still, I do have just over 800 people using it today, and its growing pretty consistently 🙂

![image](https://github.com/pcolby/nfc-quick-settings/assets/5195222/8aba4f44-df6f-4924-b33b-45d371c22edc)

And just for fun, here's a list of all the device models that currently have NFC Quick Settings installed. _Presumably_ none of these have the NFC tile built-in (otherwise what's the point of installing mine?) 🙂

> [!NOTE]  
> NFC Quick Settings does *not* track any of these details - they're standard metrics that Google Play provides for every app 😇

Manufacturer | Model Name | Install base
-- | -- | --
Google | Pixel 8 | 103
Google | Pixel 8 Pro | 98
Google | Pixel 7 | 97
Google | Pixel 7a | 59
Google | Pixel 7 Pro | 51
Google | Pixel 6a | 43
Google | Pixel 6 | 35
Google | Pixel 5 | 22
Google | Pixel 6 Pro | 18
Google | Pixel 4a | 14
Google | Pixel 4a (5G) | 11
Samsung | Galaxy Note20 Ultra 5G | 6
Sony | Xperia 1 V | 6
Nokia | Nokia G22 | 6
Sony | Xperia 1 III | 4
Redmi | Redmi Note 8 Pro | 4
Samsung | Galaxy A53 5G | 4
Samsung | Galaxy S23+ | 4
Sony | Xperia 10 V | 4
Huawei | P20 lite | 4
Google | Pixel Fold | 4
Sony | Xperia 5 II | 3
Sony | Xperia 10 III | 3
Google | Pixel 2 | 3
Sony | Xperia 10 IV | 3
Redmi | Redmi Note 12 Pro+ 5G | 3
Google | Pixel 3a | 3
Sony | Xperia 5 V | 3
Google | Pixel 5a 5G | 3
Sony | Xperia 5 IV | 3
Sony | Xperia 1 V | 3
Samsung | Galaxy Z Flip3 5G | 3
Samsung | Galaxy S23 Ultra | 3
Sony | Xperia 5 IV | 3
Google | Pixel 3 XL | 2
Redmi | Redmi Note 11S | 2
Redmi | Redmi Note 11 | 2
Fujitsu | F-04K | 2
Nokia | Nokia G21 | 2
Redmi | Redmi 13C | 2
Samsung | Galaxy S21 Ultra 5G | 2
Sony | Xperia 5 IV | 2
Surface | Surface Duo 2 | 2
Samsung | Galaxy S9+ | 2
Google | Pixel 2 XL | 2
Umidigi | BISON | 2
LGE | LG Q9 One | 2
Redmi | Redmi 10C | 2
Sony | Xperia 1 IV | 2
Redmi | Redmi Note 11 Pro | 2
Huawei | Mate 20 Pro | 2
OnePlus | OnePlus 9 Pro 5G | 2
Huawei | Honor 7C | 2
Nokia | Nokia 7.2 | 2
Samsung | Galaxy A24 | 2
Sharp | AQUOS sense8 | 2
Samsung | Galaxy A14 5G | 2
Samsung | Galaxy M23 5G | 2
Google | Pixel 4 | 2
Samsung | Galaxy Z Fold3 5G | 2
Redmi | Redmi Note 12 | 2
Huawei | P30 Pro | 2
Huawei | Honor 10 | 2
OnePlus | OnePlus 8 Pro | 2
Xiaomi | Mi 10T Pro | 2
Tecno | TECNO POVA 4 Pro | 1
Sony | Xperia 10 IV | 1
Samsung | Galaxy S10 5G | 1
OnePlus | OnePlus 8T | 1
Sony | Xperia 10 IV | 1
Sharp | AQUOS sense4 lite SH-RM15 | 1
Blackview | BV5900 | 1
Sharp | AQUOS sense7 plus | 1
Samsung | Galaxy S20 FE 5G | 1
Xiaomi | Xiaomi 13T | 1
Oukitel | K15_Plus_RU | 1
Motorola | Moto X (4) | 1
Motorola | moto g(50) | 1
Samsung | Galaxy A32 | 1
Redmi | Redmi Note 11 Pro 5G | 1
OnePlus | OnePlus 7T | 1
Nokia | Nokia 6.1 | 1
Samsung | Galaxy S7 edge | 1
Oppo | OPPO Reno7 A | 1
OnePlus | OnePlus Nord N10 5G | 1
Redmi | Redmi Note 9 Pro | 1
Motorola | motorola one vision | 1
Blackview | Blackview BV9500 | 1
Tecno | CAMON 20 Pro | 1
OnePlus | OnePlus Nord | 1
Xiaomi | Mi 5s | 1
Huawei | honor 10 Lite | 1
Deutsche Telekom | T Phone Pro | 1
Samsung | Galaxy S8 | 1
Cricket | Cricket® Dream 5G | 1
Samsung | Galaxy Note9 | 1
Samsung | Galaxy Note10+ 5G | 1
F150 | B2021 | 1
Samsung | Galaxy A30s | 1
Sony | Xperia 1 III | 1
Samsung | Galaxy A34 5G | 1
Honor | HONOR 90 | 1
Oppo | Find X3 Pro | 1
Nokia | Nokia 8.3 5G | 1
Motorola | moto g84 5G | 1
Huawei | P20 | 1
Sony | Xperia 1 IV | 1
Mode1 | MD06P | 1
Sony | Xperia 1 II | 1
Xiaomi | Mi 10T Lite | 1
Sharp | AQUOS R8 pro | 1
Nokia | Nokia 6.2 | 1
Nokia | Nokia G21 | 1
Sony | Xperia 5 II | 1
Nokia | Nokia 5.3 | 1
Samsung | Galaxy A51 | 1
POCO | POCO X3 NFC | 1
POCO | POCO F5 | 1
Oukitel | S118_RU | 1
Samsung | Galaxy S21 FE 5G | 1
Samsung | Galaxy Note10+ | 1
Sony | Xperia Z5 | 1
Samsung | Galaxy S23 | 1
Huawei | Honor 9 Lite | 1
Samsung | Galaxy S21 5G | 1
OnePlus | OnePlus 9R | 1
Nokia | Nokia 3.4 | 1
Samsung | Galaxy A40 | 1
RED | H1A1000 | 1
Motorola | moto g(6) | 1
Motorola | motorola edge 40 pro | 1
Umidigi | Power_3_EEA | 1
Redmi | Redmi Note 12 Pro | 1
Samsung | Galaxy A33 5G | 1
Doogee | S100 | 1
fplus | H166 | 1
Sony | Xperia 5 IV | 1
Xiaomi | Xiaomi 12T Pro | 1
Sony | Xperia 5 III | 1
BALMUDA | BALMUDA Phone | 1
Honor | HONOR 70 | 1
Oukitel | K6 | 1
Sony | Xperia 1 II | 1
Honor | HONOR 90 Lite | 1
Motorola | moto g(6) plus | 1
Sony | Xperia 10 II | 1
Asus | ZenFone 5 Lite (ZC600KL) | 1
Samsung | Galaxy A23 5G | 1
Samsung | Galaxy S22 | 1
Sony | Xperia XZ2 Compact | 1
Tecno | TECNO SPARK 10C | 1
T-Mobile | REVVL 6 Pro | 1
Kyocera | DuraForce PRO 3 | 1
Sharp | AQUOS zero6 | 1
Sharp | AQUOS zero6 | 1
Tecno | TECNO | 1
Sony | Xperia 10 V | 1

Cheers.

**Comment by pitsi** [comment]
The button is missing on PIXELS?!?! Is that on android 13/14 only or in older versions too? What percentage of those devices are pixels? My estimate is 25-30%, but I can not export the table to an excel file and do calculations right now.

It just proved the words "when missing functionality is a feature" that I sometimes use for stuff created by google and ms. At least the guy from google did not give a lame excuse for it. Some fanboys definitely would.

As for the devices, I am pretty sure there was a button on the stock, android 11 rom of my a40 (the one that now has crdroid), and there is definitely one on my nokia 5. I will also check a nokia 6.1 once I contact an old lady who owns it.

If you have nothing else to add, feel free to close it now that my question is answered. Thank you :)

**Comment by pitsi** [comment]
A few hours ago I got my hands on that nokia 6.1. And indeed it has no nfc toggle!
(shocked_pikachu_face.png)

**Comment by pitsi** [comment]
Please do not make fun of me...

I visited a friend who owns a pixel 6a and checked if it did have the nfc toggle. It did not. And my friend said "does yours have it?". It turns out that neither my hokia 5 has it! I mistook it with a similar one I guess :(

So, I installed your app and got the toggle, but when I press it, it just gets me straight to settings > connected devices. If this is a bug or I am missing something, please tell me how can I make it work properly.
