### ISSUE TITLE
Tile is just a shortcut to settings ?

### ISSUE THREAD

**Issue by adribtg** [pcolby/nfc-quick-settings#18]
Hi,

First of all thank you for your app.
When I click on the nfc tile made by your app, it's just opening the settings and I have to turn on NFC by myself.

Is there any way to just switch, without opening the settings ?

**Comment by pcolby** [comment]
> First of all thank you for your app.

You're very welcome 😊

> Is there any way to just switch, without opening the settings?

Unfortunately not. As per the "About this app" description:

> Android security limitations do not allow any third-party apps, such as this, to turn NFC on or off directly, so when tapped, the NFC Quick Settings tile will simply open the device's NFC Settings page (if the device has one), where you can enable or disable NFC as desired.

😞

If Android ever allows me to turn NFC on/off directly, I'll implement it ASAP - I want it for myself! 😄 But I understand its a privacy concern for Android, since NFC can be used to track people. I reckon Android should be able to allow it when it's in response to a direct user interaction, but I'm sure it's a low priority for Google/Android.

Cheers.

**Comment by adribtg** [comment]
Hi Paul,
Thank you for your quick answer.
I saw on another repository, someone requesting a permission with adb which looks like 
`adb shell pm grant appname android.permission.WRITE_SECURE_SETTINGS.`
Do you think there's a possibility to manually install the app and grant this permission? Could it work?

**Comment by pcolby** [comment]
Hi @adribtg, that's very interesting 🤔 I'm not sure what capability that permission gives, but I will definitely look into it this weekend 😄 Thanks!

**Comment by adribtg** [comment]
For more information, I finally managed to make it works manually with this repository :
https://github.com/Docheinstein/nfc-tile
The only remaining bug I have is that the tile shows that NFC is on while it's off, and off while it's on, but it works !

**Comment by pcolby** [comment]
Hey @adribtg, I know this has been a while, but I've finally implemented support for using the `WRITE_SECURE_SETTINGS` permission, if/when granted.  And frankly, it works really nicely, so thank you!! 😄

I've also switched out an internal timer for a broadcast receiver instead. The receiver is much more responsive, which doesn't really matter when opening the NFC Settings action, but makes a big different when using the `WRITE_SECURE_SETTINGS` to toggle the adapter directly.

Anyway, the changes are in `main` now.  I'll do a bit of testing over the next couple of days, update the docs, then release to the internal, and open testing channels in the Play store.

Cheers!

**Comment by adribtg** [comment]
Very nice to hear from you, thanks a lot for your work ! 😄

**Comment by pcolby** [comment]
This has now been released in v1.4.0.  The release is also available to open and closed testers via Google Play, and a "production" rollout is being staged by Google Play (currently at 10%).

If you're in a hurry, you can join the open testing track via: https://play.google.com/apps/testing/au.id.colby.nfcquicksettings Otherwise just wait for the eventual rollout to your device.

(And if you're really keen, I'm happy to add people to the internal testing track too - you'd just have to give me an email address to invite).

Cheers.

**Comment by pergolafabio** [comment]
Hi, I am on 1.4.3, but if I click on the tile, it still redirects me to the NFC setting?

**Comment by pergolafabio** [comment]
Woops, sorry, I didn't read the info :-)
Gonna try the adb command tomorrow!!
